### ISSUE TITLE
Consider relationship between Mesa model and NetLogo model

### ISSUE THREAD

**Issue by MarkLTurner** [DurhamARC/classroom-abm#42]
Subproblems to address here include:
- [x] Random number variable (currently `randomised_agent_attribute`) is generated at each step and therefore the same number is used for each random decision. In NetLogo a new random number is generated at each decision point within each agent step. Consideration as to which way is the best way forward would be good.
- [x] A pipeline to read in full dataset is required. A feature to vary the size of the input dataset would be useful too. (See #44)
- [x] The ability to vary class sizes in the model is required. In connection with this, we will also need to be able to vary the size of pupil groupings within a single class. (See #44)
- [x] The model should output data in the same format as the input file, as NetLogo does, in order for the multilevel analysis to be run. (See #44)
- [x] The existing NetLogo model doesn't consider time spent by an agent in a given state as relevant to the step logic. By contrast, in the Mesa model, agents keep track of the time they spend in a given state and use this influence their learning status going forward. The intuition here is that this logic can cover cases such as: if a pupil is learning for some amount of time, eventually they will click into a passive or disruptive state as they can't focus forever.

Finally, 
 - [x] Present the logic of the pupil's step to Peter and seek approval. Perhaps comments in the code are enough; if not, let's summarise the logic in an email.

**Comment by alisonrclarke** [comment]
After discussions with Peter we are going to convert the current pupil step in the NetLogo model directly to the Mesa model.

**Comment by alisonrclarke** [comment]
Think all these issues are now covered by other issues e.g. #65
